apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app.kubernetes.io/name: {{ include "container.name" . }}
    helm.sh/chart: {{ include "container.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: {{ include "container.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
